name: Docker develop build

on:
  push:
    branches:
      - main

jobs:
  docker-cache:
    uses: TrustlessComputer-DevOps/tc-github-action-templates/.github/workflows/docker-build-cache.yaml@main
    with:
      DOCKER_IMAGE_NAME: bvm-website-sats
      DOCKERFILE_NAME: Dockerfile.cache

